apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-prometheus
  namespace: showks-system
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: grafana
