---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    nginx.org/ssl-services: weavescope
  name: weavescope
  namespace: showks-system
spec:
  rules:
  - host: weavescope.__DOMAIN__
    http:
      paths:
      - backend:
          serviceName: weave-scope-app
          servicePort: 80
        path: /
  tls:
  - hosts:
    - weavescope.__DOMAIN__
    secretName: showks-system/tls-certificate
