---
apiVersion: v1
data:
  tls.crt: __TLS_CRT__
  tls.key: __TLS_KEY__
kind: Secret
metadata:
  name: tls-certificate
  namespace: showks-system
---
apiVersion: v1
data:
  tls.crt: __TLS_CRT__
  tls.key: __TLS_KEY__
kind: Secret
metadata:
  name: tls-certificate
  namespace: showks
