---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    nginx.org/ssl-services: keycloak
  name: keycloak
  namespace: showks-system
spec:
  rules:
  - host: keycloak.__DOMAIN__
    http:
      paths:
      - backend:
          serviceName: keycloak-http
          servicePort: 80
        path: /
  tls:
  - hosts:
    - keycloak.__DOMAIN__
    secretName: tls-certificate
