---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-form
  labels:
    app: showks-form
  namespace: showks-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-form
  template:
    metadata:
      labels:
        app: showks-form
    spec:
      containers:
      - name: showks-form
        image: cloudnativedaysjp/showks-form:stg-4c8a5448a0bf0cd655908b1c869b9ee113b6af1c
        env:
          - name: RAILS_ENV
            value: "production"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          - name: IN_CLUSTER
            value: "true"
          - name: WEBHOOK_TOKEN
            valueFrom:
              secretKeyRef:
                name: showks-secret
                key: WEBHOOK_TOKEN
          - name: REGISTRY_USERNAME
            valueFrom:
              secretKeyRef:
                name: showks-form
                key: REGISTRY_USERNAME
          - name: REGISTRY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: showks-secret
                key: REGISTRY_PASSWORD
          - name: REGISTRY_URL
            valueFrom:
              secretKeyRef:
                name: showks-secret
                key: REGISTRY_URL
          - name: GITHUB_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: showks-secret
                key: GITHUB_ACCESS_TOKEN
          - name: GITHUB_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: showks-secret
                key: GITHUB_PRIVATE_KEY
          - name: GITHUB_ORG
            valueFrom:
              secretKeyRef:
                name: showks-secret
                key: GITHUB_ORG
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: showks-form
  name: showks-form
  namespace: showks-system
spec:
  ports:
  - name: app-port
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: showks-form
  type: ClusterIP
