---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
  name: showks-form
  namespace: showks-system
spec:
  rules:
  - host: form.__DOMAIN__
    http:
      paths:
      - backend:
          serviceName: showks-form
          servicePort: 3000
        path: /
  tls:
  - hosts:
    - form.__DOMAIN__
    secretName: showks-system/tls-certificate
